### ISSUE TITLE
Error, running Inpactor. 

### ISSUE THREAD

**Issue by caixu0518** [simonorozcoarias/Inpactor#1]
Hi，

Error message when running Inpactor.  

(standard_in) 2: syntax error
(standard_in) 2: syntax error
(standard_in) 2: syntax error
(standard_in) 2: syntax error
(standard_in) 2: syntax error
(standard_in) 2: syntax error

Best,
Xu

**Comment by simonorozcoarias** [comment]
Hi,

Thank you for using Inpactor. Can you attach to this issue your configuration file and the complete error output?

Which step was running when Inpactor failed? Which version of Bash was used?

Best,

Simon Orozco-Arias

**Comment by caixu0518** [comment]
Hello Simon,

Thank you so much for your reply. The following is specific information.

bash:   4.2.46(2)-release (x86_64-redhat-linux-gnu)

**Log information:**
 
Reading configuration file: BRO_conf_file ...
Input is: /TE/Inpactor/YDLcaixin_BRO_v1.0_asm.fasta
Result directory is: /TE/Inpactor/BRO_Inpactor
verbose was actived? true
clean was actived? true
Input Type is: fasta
preprocessing module 1 was selected? true
database is: /tools/Inpactor/Inpactor/cores-database-wickercode.fasta
Classification module was selected? true
tabfile is: 
80-80-80 rule is enabled? true
Extraction module was selected? true
RT database is: /tools/Inpactor/Inpactor/RTcores-database-wickercode.fasta
references are: 
fastafile is: 
RT length is: 200
BLAST E-value is: 1e-4
Insertion module was selected? true
substitution rate is: 0.000000013
tabular file for step 4 is: 
finished reading configuration file
Creating result directory: mkdir -p /TE/Inpactor/BRO_Inpactor
Creating step 1 directory
executing command: sh Parallel_splitter  /TE/Inpactor/BRO_Inpactor/step1 /TE/Inpactor/YDLcaixin_BRO_v1.0_asm.fasta 11 5
there are 3653 sequences.

each process has to analyze approximately 332 sequences

executing command: sh functions step1_fasta /TE/Inpactor/YDLcaixin_BRO_v1.0_asm.fasta /tools/Inpactor/Inpactor/cores-database-wickercode.fasta 9 /TE/Inpactor/BRO_Inpactor/step1
executing command: sh functions step1_fasta /TE/Inpactor/YDLcaixin_BRO_v1.0_asm.fasta /tools/Inpactor/Inpactor/cores-database-wickercode.fasta 10 /TE/Inpactor/BRO_Inpactor/step1
executing command: sh functions step1_fasta /TE/Inpactor/YDLcaixin_BRO_v1.0_asm.fasta /tools/Inpactor/Inpactor/cores-database-wickercode.fasta 11 /TE/Inpactor/BRO_Inpactor/step1
executing command: sh functions step1_fasta /TE/Inpactor/YDLcaixin_BRO_v1.0_asm.fasta /tools/Inpactor/Inpactor/cores-database-wickercode.fasta 1 /TE/Inpactor/BRO_Inpactor/step1
executing command: sh functions step1_fasta /TE/Inpactor/YDLcaixin_BRO_v1.0_asm.fasta /tools/Inpactor/Inpactor/cores-database-wickercode.fasta 2 /TE/Inpactor/BRO_Inpactor/step1
executing command: sh functions step1_fasta /TE/Inpactor/YDLcaixin_BRO_v1.0_asm.fasta /tools/Inpactor/Inpactor/cores-database-wickercode.fasta 3 /TE/Inpactor/BRO_Inpactor/step1
executing command: sh functions step1_fasta /TE/Inpactor/YDLcaixin_BRO_v1.0_asm.fasta /tools/Inpactor/Inpactor/cores-database-wickercode.fasta 4 /TE/Inpactor/BRO_Inpactor/step1
executing command: sh functions step1_fasta /TE/Inpactor/YDLcaixin_BRO_v1.0_asm.fasta /tools/Inpactor/Inpactor/cores-database-wickercode.fasta 5 /TE/Inpactor/BRO_Inpactor/step1
executing command: sh functions step1_fasta /TE/Inpactor/YDLcaixin_BRO_v1.0_asm.fasta /tools/Inpactor/Inpactor/cores-database-wickercode.fasta 6 /TE/Inpactor/BRO_Inpactor/step1
executing command: sh functions step1_fasta /TE/Inpactor/YDLcaixin_BRO_v1.0_asm.fasta /tools/Inpactor/Inpactor/cores-database-wickercode.fasta 7 /TE/Inpactor/BRO_Inpactor/step1
executing command: sh functions step1_fasta /TE/Inpactor/YDLcaixin_BRO_v1.0_asm.fasta /tools/Inpactor/Inpactor/cores-database-wickercode.fasta 8 /TE/Inpactor/BRO_Inpactor/step1

**(standard_in) 2: syntax error
(standard_in) 2: syntax error
(standard_in) 2: syntax error
(standard_in) 2: syntax error
(standard_in) 2: syntax error
(standard_in) 2: syntax error
(standard_in) 2: syntax error
(standard_in) 2: syntax error
(standard_in) 2: syntax error
(standard_in) 2: syntax error**


Best，
Xu

**Comment by caixu0518** [comment]
In addition, when the given number of threads (id_proc, np number) contains a sequence without an LTR,
  Step2 will generate an error message. (For example, id_proc=2, step 1 will not generate out_file.2.tab, grep in step 2 will say cannot find out_file.2.tab). The following is the specific log information.


Reading configuration file: test_conf_file ...
Input is: /TE/Inpactor/test.fasta
Result directory is: /TE/Inpactor/test_Inpactor
verbose was actived? true
clean was actived? true
Input Type is: fasta
preprocessing module 1 was selected? true
database is: /tools/Inpactor/Inpactor/cores-database-wickercode.fasta
Classification module was selected? true
tabfile is: 
80-80-80 rule is enabled? true
Extraction module was selected? true
RT database is: /tools/Inpactor/Inpactor/RTcores-database-wickercode.fasta
references are: 
fastafile is: 
RT length is: 200
BLAST E-value is: 1e-4
Insertion module was selected? true
substitution rate is: 0.000000013
tabular file for step 4 is: 
finished reading configuration file
Creating result directory: mkdir -p /TE/Inpactor/test_Inpactor
Creating step 1 directory
executing command: sh Parallel_splitter  /TE/Inpactor/test_Inpactor/step1 /TE/Inpactor/test.fasta 5 5
there are 10 sequences.

each process has to analyze approximately 2 sequences

executing command: sh functions step1_fasta /TE/Inpactor/test.fasta /tools/Inpactor/Inpactor/cores-database-wickercode.fasta 1 /TE/Inpactor/test_Inpactor/step1
executing command: sh functions step1_fasta /TE/Inpactor/test.fasta /tools/Inpactor/Inpactor/cores-database-wickercode.fasta 2 /TE/Inpactor/test_Inpactor/step1
executing command: sh functions step1_fasta /TE/Inpactor/test.fasta /tools/Inpactor/Inpactor/cores-database-wickercode.fasta 3 /TE/Inpactor/test_Inpactor/step1
executing command: sh functions step1_fasta /TE/Inpactor/test.fasta /tools/Inpactor/Inpactor/cores-database-wickercode.fasta 4 /TE/Inpactor/test_Inpactor/step1
executing command: sh functions step1_fasta /TE/Inpactor/test.fasta /tools/Inpactor/Inpactor/cores-database-wickercode.fasta 5 /TE/Inpactor/test_Inpactor/step1
proc 1 done!
proc 2 done!
proc 3 done!
proc 4 done!
proc 5 done!
executing command: cat  /TE/Inpactor/test_Inpactor/step1/out_file.*.tab > /TE/Inpactor/test_Inpactor/step1/all_tabfiles.tab
Preprocessing done, please check file: /TE/Inpactor/test_Inpactor/step1/all_tabfiles.tab
Creating step 2 directory
executing command: sh functions  step2 /TE/Inpactor/test_Inpactor/step1 5 /TE/Inpactor/test_Inpactor/step2
executing command: sh functions  step2 /TE/Inpactor/test_Inpactor/step1 1 /TE/Inpactor/test_Inpactor/step2
executing command: sh functions  step2 /TE/Inpactor/test_Inpactor/step1 2 /TE/Inpactor/test_Inpactor/step2
executing command: sh functions  step2 /TE/Inpactor/test_Inpactor/step1 3 /TE/Inpactor/test_Inpactor/step2
executing command: sh functions  step2 /TE/Inpactor/test_Inpactor/step1 4 /TE/Inpactor/test_Inpactor/step2
**grep: /TE/Inpactor/test_Inpactor/step1/out_file.2.tab: No such file or directory**
**sed：Unable to read /TE/Inpactor/test_Inpactor/step1/out_file.2.tab：No such file or directory**
functions:行608: /TE/Inpactor/test_Inpactor/step2/out_file.2.tab_ALL.RLC_RLG.TAB.families: No such file or directory
functions:行608: /TE/Inpactor/test_Inpactor/step2/out_file.4.tab_ALL.RLC_RLG.TAB.families: No such file or directory
proc 1 done!
proc 2 done!
proc 3 done!
proc 4 done!
proc 5 done!
executing command: cat  /TE/Inpactor/test_Inpactor/step2/out_file.*.tab_ALL.RLC_RLG.TAB > /TE/Inpactor/test_Inpactor/step2/all_tabfiles.tab_ALL.RLC_RLG.TAB; cat /TE/Inpactor/test_Inpactor/step2/out_file.*.tab_ALL.RLC_RLG.FA > /TE/Inpactor/test_Inpactor/step2/all_tabfiles.tab_ALL.RLC_RLG.FA; cat /TE/Inpactor/test_Inpactor/step2/out_file.*.tab.RXX.TAB > /TE/Inpactor/test_Inpactor/step2/all_tabfiles.tab_ALL.RXX.TAB; cat /TE/Inpactor/test_Inpactor/step2/out_file.*.tab.RXX.FA > /TE/Inpactor/test_Inpactor/step2/all_tabfiles.tab_ALL.RXX.FA; cat /TE/Inpactor/test_Inpactor/step2/out_file.*.tab.TR_GAG.TAB > /TE/Inpactor/test_Inpactor/step2/all_tabfiles.tab_ALL.TR_GAG.TAB; cat /TE/Inpactor/test_Inpactor/step2/out_file.*.tab.TR_GAG.FA > /TE/Inpactor/test_Inpactor/step2/all_tabfiles.tab_ALL.TR_GAG.FA; cat /TE/Inpactor/test_Inpactor/step2/out_file.*.tab.NOC.TAB > /TE/Inpactor/test_Inpactor/step2/all_tabfiles.tab.NOC.TAB; cat /TE/Inpactor/test_Inpactor/step2/out_file.*.tab.NOC.FA > /TE/Inpactor/test_Inpactor/step2/all_tabfiles.tab.NOC.FA; cat /TE/Inpactor/test_Inpactor/step2/out_file.*.tab_ALL.RLC_RLG.TAB.families > /TE/Inpactor/test_Inpactor/step2/all_tabfiles.tab_ALL.RLC_RLG.TAB.families; cat /TE/Inpactor/test_Inpactor/step2/out_file.*.tab_ALL.RLC_RLG.TAB.families.FA > /TE/Inpactor/test_Inpactor/step2/all_tabfiles.tab_ALL.RLC_RLG.TAB.families.FA; cat /TE/Inpactor/test_Inpactor/step2/all_tabfiles.tab_ALL.RLC_RLG.TAB.families.FA /TE/Inpactor/test_Inpactor/step2/all_tabfiles.tab_ALL.RXX.FA /TE/Inpactor/test_Inpactor/step2/all_tabfiles.tab_ALL.TR_GAG.FA > /TE/Inpactor/test_Inpactor/step2/classifiedTE.fa;
cat: /TE/Inpactor/test_Inpactor/step2/out_file.*.tab.NOC.FA: No such file or directory
executing command: sh functions  80-80-80-law /TE/Inpactor/test_Inpactor/step1 5 /TE/Inpactor/test_Inpactor/step2
executing command: sh functions  80-80-80-law /TE/Inpactor/test_Inpactor/step1 4 /TE/Inpactor/test_Inpactor/step2
executing command: sh functions  80-80-80-law /TE/Inpactor/test_Inpactor/step1 1 /TE/Inpactor/test_Inpactor/step2
executing command: sh functions  80-80-80-law /TE/Inpactor/test_Inpactor/step1 2 /TE/Inpactor/test_Inpactor/step2
executing command: sh functions  80-80-80-law /TE/Inpactor/test_Inpactor/step1 3 /TE/Inpactor/test_Inpactor/step2
proc 1 done!
proc 2 done!
proc 3 done!
proc 4 done!
proc 5 done!
executing command: cat  /TE/Inpactor/test_Inpactor/step2/out_file.*.tab_ALL.RLC_RLG.TAB > /TE/Inpactor/test_Inpactor/step2/all_tabfiles.tab_ALL.RLC_RLG.TAB; cat /TE/Inpactor/test_Inpactor/step2/out_file.*.tab_ALL.RLC_RLG.FA > /TE/Inpactor/test_Inpactor/step2/all_tabfiles.tab_ALL.RLC_RLG.FA; cat /TE/Inpactor/test_Inpactor/step2/out_file.*.tab.RXX.TAB > /TE/Inpactor/test_Inpactor/step2/all_tabfiles.tab_ALL.RXX.TAB; cat /TE/Inpactor/test_Inpactor/step2/out_file.*.tab.RXX.FA > /TE/Inpactor/test_Inpactor/step2/all_tabfiles.tab_ALL.RXX.FA; cat /TE/Inpactor/test_Inpactor/step2/out_file.*.tab.TR_GAG.TAB > /TE/Inpactor/test_Inpactor/step2/all_tabfiles.tab_ALL.TR_GAG.TAB; cat /TE/Inpactor/test_Inpactor/step2/out_file.*.tab.TR_GAG.FA > /TE/Inpactor/test_Inpactor/step2/all_tabfiles.tab_ALL.TR_GAG.FA; cat /TE/Inpactor/test_Inpactor/step2/out_file.*.tab.NOC.TAB > /TE/Inpactor/test_Inpactor/step2/all_tabfiles.tab.NOC.TAB; cat /TE/Inpactor/test_Inpactor/step2/out_file.*.tab.NOC.FA > /TE/Inpactor/test_Inpactor/step2/all_tabfiles.tab.NOC.FA; cat /TE/Inpactor/test_Inpactor/step2/out_file.*.tab_ALL.RLC_RLG.TAB.families > /TE/Inpactor/test_Inpactor/step2/all_tabfiles.tab_ALL.RLC_RLG.TAB.families; cat /TE/Inpactor/test_Inpactor/step2/out_file.*.tab_ALL.RLC_RLG.TAB.families.FA > /TE/Inpactor/test_Inpactor/step2/all_tabfiles.tab_ALL.RLC_RLG.TAB.families.FA; cat /TE/Inpactor/test_Inpactor/step2/all_tabfiles.tab_ALL.RLC_RLG.TAB.families.FA /TE/Inpactor/test_Inpactor/step2/all_tabfiles.tab_ALL.RXX.FA /TE/Inpactor/test_Inpactor/step2/all_tabfiles.tab_ALL.TR_GAG.FA > /TE/Inpactor/test_Inpactor/step2/classifiedTE.fa;
cat: /TE/Inpactor/test_Inpactor/step2/out_file.*.tab.NOC.FA: No such file or directory
Classification done, please check files in /TE/Inpactor/test_Inpactor/step2
Creating step 3 directory
fasta file: /TE/Inpactor/test_Inpactor/step2/all_tabfiles.tab_ALL.RLC_RLG.FA
executing command: sh Parallel_splitter  /TE/Inpactor/test_Inpactor/step2 /TE/Inpactor/test_Inpactor/step2/all_tabfiles.tab_ALL.RLC_RLG.FA 5 3 ''
there are 17 sequences.

each process has to analyze approximately 3 sequences

executing command: sh functions  step3 /tools/Inpactor/Inpactor/RTcores-database-wickercode.fasta 2 /TE/Inpactor/test_Inpactor/step3 /TE/Inpactor/test_Inpactor/step2 200 1e-4
executing command: sh functions  step3 /tools/Inpactor/Inpactor/RTcores-database-wickercode.fasta 3 /TE/Inpactor/test_Inpactor/step3 /TE/Inpactor/test_Inpactor/step2 200 1e-4
executing command: sh functions  step3 /tools/Inpactor/Inpactor/RTcores-database-wickercode.fasta 5 /TE/Inpactor/test_Inpactor/step3 /TE/Inpactor/test_Inpactor/step2 200 1e-4
executing command: sh functions  step3 /tools/Inpactor/Inpactor/RTcores-database-wickercode.fasta 4 /TE/Inpactor/test_Inpactor/step3 /TE/Inpactor/test_Inpactor/step2 200 1e-4
executing command: sh functions  step3 /tools/Inpactor/Inpactor/RTcores-database-wickercode.fasta 1 /TE/Inpactor/test_Inpactor/step3 /TE/Inpactor/test_Inpactor/step2 200 1e-4
proc 1 done!
proc 2 done!
proc 3 done!
proc 4 done!
proc 5 done!
executing command: cat  /TE/Inpactor/test_Inpactor/step3/Genome.*.RT.fa /tools/Inpactor/Inpactor/RTcores-database-wickercode.fasta > /TE/Inpactor/test_Inpactor/step3/Genome.all_ALL.RLC_RLG.fa.rt
Domain Extraction done, please check file: /TE/Inpactor/test_Inpactor/step3/Genome.all_ALL.RLC_RLG.fa.rt
genome file: /TE/Inpactor/test_Inpactor/step3/Genome.all_ALL.RLC_RLG.fa.rt
Creating step 4 directory
tabfile for step 4 is: /TE/Inpactor/test_Inpactor/step2/all_tabfiles.tab_ALL.RLC_RLG.TAB
executing command: sh Parallel_splitter /TE/Inpactor/test_Inpactor/step2 /TE/Inpactor/test_Inpactor/step2/all_tabfiles.tab_ALL.RLC_RLG.TAB 5 4
there are 17 sequences.

each process has to analyze approximately 3 sequences

executing command: sh functions  step4 3 /TE/Inpactor/test_Inpactor/step4 /TE/Inpactor/test_Inpactor/step2 fasta 0.000000013
executing command: sh functions  step4 5 /TE/Inpactor/test_Inpactor/step4 /TE/Inpactor/test_Inpactor/step2 fasta 0.000000013
executing command: sh functions  step4 4 /TE/Inpactor/test_Inpactor/step4 /TE/Inpactor/test_Inpactor/step2 fasta 0.000000013
executing command: sh functions  step4 1 /TE/Inpactor/test_Inpactor/step4 /TE/Inpactor/test_Inpactor/step2 fasta 0.000000013
executing command: sh functions  step4 2 /TE/Inpactor/test_Inpactor/step4 /TE/Inpactor/test_Inpactor/step2 fasta 0.000000013
proc 2 done!
proc 3 done!
proc 4 done!
proc 5 done!
executing command: sh functions  step4 0 /TE/Inpactor/test_Inpactor/step4 /TE/Inpactor/test_Inpactor/step3/Genome.all_ALL.RLC_RLG.fa.rt 6
Distribution file done, please check file: /TE/Inpactor/test_Inpactor/step4/Distribution-in-age.tab
Tree file done, please check file: /TE/Inpactor/test_Inpactor/step4/multiple_align.tree
executing cleaner: sh functions cleaner /TE/Inpactor/test_Inpactor
Number of  Commands: 18

Best，
Xu
