### ISSUE TITLE
something wrong with invalid number of lines 

### ISSUE THREAD

**Issue by hexin010101** [simonorozcoarias/Inpactor#2]
I encountered an error 
> cat: /public/home/xhe/software/Inpactor/merge_result/step1/in_file.14.tmpcat: /public/home/xhe/software/Inpactor/merge_result/step1/in_file.17.tmp: No such file or directory
: No such file or directory
cat: /public/home/xhe/software/Inpactor/merge_result/step1/in_file.16.tmpcat: /public/home/xhe/software/Inpactor/merge_result/step1/in_file.19.tmp: No such file or directory
: No such file or directory
cat: /public/home/xhe/software/Inpactor/merge_result/step1/in_file.15.tmp: No such file or directory
cat: /public/home/xhe/software/Inpactor/merge_result/step1/in_file.18.tmp: No such file or directory
head: {i..1031..1}: invalid number of lines
head: {i..1031..1}: invalid number of lines
(standard_in) 1: syntax error
head: {i..1031..1}: invalid number of lines
head: {i..1031..1}: invalid number of lines
grep: /public/home/xhe/software/Inpactor/merge_result/step1/Chr09.LTRA.fa.tmp: No such file or directory
head: {i..1031..1}: invalid number of lines
head: {i..1031..1}: invalid number of lines
grep: /public/home/xhe/software/Inpactor/merge_result/step1/Chr09.LTRB.fa.tmp: No such file or directory
head: {i..1031..1}: invalid number of lines
head: {i..1031..1}: invalid number of lines
grep: /public/home/xhe/software/Inpactor/merge_result/step1/Chr09.{i..1031..1}.fa.tmp: No such file or directory
[blastall] FATAL ERROR: blast: Unable to open input file /public/home/xhe/software/Inpactor/merge_result/step1/Chr09.{i..1031..1}.fa.tmp

My configuration file is 
```
 input=A2.chr.fa
result_directory=/public/home/xhe/software/Inpactor/merge_result
verbose=true
clean=true
# this type can be LTR_STRUC, repet or fasta
input_type=fasta
############################# Preprocessing ###############################
preprocessing=true
# database with domain sequences
database=cores-database-wickercode.fasta
############################# Classification ################################
classification=true
# this tabfile isn't necessary if preprocessing is true
#tabfile=/home/user/result_directory/step1/all_tabfiles.tab
# for doing re classification
80-80-80-rule=false
############################# Domain Extraction ##############################
extraction=true
# database of domains that you want to extract, we recommend to use Reverse transcriptase domain (RT)
RTdatabase=RTcores-database-wickercode.fasta
# if you have already classified LTR retrotransposons, you can used them for phylogenetic analysis (optional)
#references=/home/user/result_directory/references.fasta
# this fastafile isn't necessary if classification is true
#fastafile=/home/user/result_directory/step2/all_tabfiles.tab_ALL.RLC_RLG.FA
# filter RT size. For a lot of RT, is better RTlength > 200, for less RTlength > 180 or 150
RTlength=200
Blast_evalue=1e-4
############ Insertion Time analysis and Phylogenetic tree creation #########
insertion=true
substitution_rate=0.000000007
# this tabfile isn't necessary if classification is true
#tabfileS4=/home/user/result_directory/step2/all_tabfiles.tab_ALL.RLC_RLG.TAB
```

**Comment by simonorozcoarias** [comment]
Which batch version do you have?  Try ucomment the line 118 and comment line 117.

**Comment by hexin010101** [comment]
Is it to modify the file named function? Do I still need to recompile the Inpactor executable?

**Comment by simonorozcoarias** [comment]
You must modify the script "functions". Please comment the line 119 (for i in {i..$num_eleme..1}) and ucomment the line 118 (for ((i=1; i<=$num_eleme; i++))). It is not necessary to recompile. Best wishes!

**Comment by hexin010101** [comment]
Great, thanks for the quick reply. It looks like it run successfully

**Comment by simonorozcoarias** [comment]
Thank you for using Inpactor. Best regards.
